%% ============================================================
% HIT2D spatial homogeneity
%
% 1. Select 30000 particles from the original particle set
% 2. Divide the periodic HIT domain into 4 x 4 fixed blocks
% 3. Randomly select at most max_particles_per_block particles
%    in each block at each time
% 4. Retain the original pair-distance functions:
%       dist_nogeo
%       dist_norx
%       dist_nory
%       dist_du
% 5. No bootstrap and no storage of all particle pairs
%% ============================================================

clear;
close all;
clc;

%% 1. Paths

addpath( ...
    '/meddy/simingzhang/Analysis/matlab/Parcels_SF/');

input_dir = ...
    '/meddy/simingzhang/Data/Parcels_data/HIT2d_rough/';

addpath(input_dir);

%% 2. Basic settings

Case = 'HIT2d';

nparticles_file = 62500;
num_to_select = 30000;

seconds = 20.0;
dt = 0.1;

timerange = 50:150;

% Reproducible random particle selection
rng(20260908);

%% 3. Spatial-block settings

nblock_x = 4;
nblock_y = 4;

% Maximum particles used in one block at one time.
% 300: about 45,000 pairs/block/time
% 400: about 80,000 pairs/block/time
% 500: about 125,000 pairs/block/time
max_particles_per_block = 400;

% Minimum accumulated number of pairs per scale/block
min_pairs = 5000;

% At least half of the 16 blocks must be valid
min_valid_blocks = 8;

%% 4. Input filename

fname = [ ...
    input_dir, ...
    Case, ...
    '_pars_P', ...
    num2str(nparticles_file), ...
    'T', ...
    num2str(seconds), ...
    '.0seconds.nc'];

fprintf('Reading:\n%s\n',fname);

%% 5. Read trajectory and velocity data

lon_all = ncread(fname,'lon');
lat_all = ncread(fname,'lat');

ue_all = ncread(fname,'ue');
ve_all = ncread(fname,'ve');

nParticleAvailable = size(lon_all,2);

if num_to_select > nParticleAvailable
    error( ...
        'Requested %d particles, but only %d are available.', ...
        num_to_select,nParticleAvailable);
end

%% 6. Select the same 30000 particles for all times

selected_indices = randperm( ...
    nParticleAvailable, ...
    num_to_select);

lon = lon_all(timerange,selected_indices);
lat = lat_all(timerange,selected_indices);

u = ue_all(timerange,selected_indices);
v = ve_all(timerange,selected_indices);

clear lon_all lat_all ue_all ve_all;

nTime = size(lon,1);
nParticle = size(lon,2);

fprintf('Selected data: %d times x %d particles\n', ...
    nTime,nParticle);

%% 7. Optional: calculate Th_all using the same particles
%
% This retains your original coarse-graining sampling.
% th_tmp is cleared after every scale, avoiding 38 large th arrays.

xscale = [ ...
    2:18, ...
    21:3:48, ...
    54:6:120, ...
    132:12:240, ...
    264:24:504];

Th_all = nan(length(xscale),nTime);

for iii = 1:length(xscale)

    pistr = ['th',num2str(xscale(iii))];

    th_tmp = ncread(fname,pistr);

    Th_all(iii,:) = mean( ...
        th_tmp(timerange,selected_indices), ...
        2, ...
        'omitnan');

    clear th_tmp;
end

%% 8. Fixed periodic-domain boundaries
%
% HIT particles should fill the entire periodic domain.
% These limits are inferred from all selected positions.
%
% If the exact simulation domain is known, it is better to specify:
%
% x_domain = [0, 2*pi];
% y_domain = [0, 2*pi];
%
% or:
%
% x_domain = [-pi, pi];
% y_domain = [-pi, pi];

x_domain = [ ...
    min(lon(:),[],'omitnan'), ...
    max(lon(:),[],'omitnan')];

y_domain = [ ...
    min(lat(:),[],'omitnan'), ...
    max(lat(:),[],'omitnan')];

x_edges = linspace( ...
    x_domain(1), ...
    x_domain(2), ...
    nblock_x+1);

y_edges = linspace( ...
    y_domain(1), ...
    y_domain(2), ...
    nblock_y+1);

nBlock = nblock_x*nblock_y;

fprintf('x domain: %.6f to %.6f\n', ...
    x_domain(1),x_domain(2));

fprintf('y domain: %.6f to %.6f\n', ...
    y_domain(1),y_domain(2));

%% 9. Original HIT distance bins

gamma = 1.2;

dist_bin = 0.0123*gamma.^(0:100);

first_large = find(dist_bin>3.14,1);

if isempty(first_large)
    error('Distance bins do not reach 3.14.');
end

dist_bin = dist_bin(1:first_large-1);

dist_bin(2:end+1) = dist_bin(1:end);

% Retained from your original code
dist_bin(1) = dist_bin(3)-dist_bin(2);

dist_axis = ...
    0.5*(dist_bin(1:end-1)+dist_bin(2:end));

nScale = length(dist_axis);

fprintf('Number of distance bins: %d\n',nScale);

%% 10. Streaming accumulators
%
% Dimensions:
%   nScale x nBlock
%
% These arrays do not grow with time.

sum_SF1_block = zeros(nScale,nBlock);
sum_SF2_block = zeros(nScale,nBlock);
sum_SF3_block = zeros(nScale,nBlock);

pair_count = zeros(nScale,nBlock);

% Overall estimates from the same block-balanced subsampling
sum_SF1_total = zeros(nScale,1);
sum_SF2ll_total = zeros(nScale,1);
sum_SF2tt_total = zeros(nScale,1);
sum_SF3lll_total = zeros(nScale,1);
sum_SF3ltt_total = zeros(nScale,1);

count_total = zeros(nScale,1);

% Record how many particles were used
particle_count = zeros(nTime,nBlock);

%% 11. Main loop: time -> spatial block

tic;

for it = 1:nTime

    fprintf('Time %d / %d\n',it,nTime);

    valid_particle = ...
        isfinite(lon(it,:)) & ...
        isfinite(lat(it,:)) & ...
        isfinite(u(it,:)) & ...
        isfinite(v(it,:));

    if sum(valid_particle)<2
        continue;
    end

    % Assign particles to fixed spatial blocks
    block_x_all = discretize( ...
        lon(it,:), ...
        x_edges);

    block_y_all = discretize( ...
        lat(it,:), ...
        y_edges);

    % Include points exactly at the upper boundary
    block_x_all( ...
        lon(it,:)==x_edges(end)) = nblock_x;

    block_y_all( ...
        lat(it,:)==y_edges(end)) = nblock_y;

    particle_block = ...
        (block_x_all-1)*nblock_y+block_y_all;

    for ib = 1:nBlock

        id = find( ...
            valid_particle & ...
            particle_block==ib);

        nAvailable = length(id);

        if nAvailable<2
            continue;
        end

        %% Limit pair calculation cost

        if nAvailable>max_particles_per_block

            local_selection = randperm( ...
                nAvailable, ...
                max_particles_per_block);

            id = id(local_selection);
        end

        particle_count(it,ib) = length(id);

        %% Variables for this block

        X = lon(it,id)';
        Y = lat(it,id)';

        U_now = u(it,id)';
        V_now = v(it,id)';

        Xvec = [X,Y];

        %% Original HIT pair functions: unchanged

        dist_now = pdist( ...
            Xvec, ...
            @dist_nogeo);

        rx = pdist( ...
            Xvec, ...
            @dist_norx);

        ry = pdist( ...
            Xvec, ...
            @dist_nory);

        magr = sqrt(rx.^2+ry.^2);

        rx = rx./magr;
        ry = ry./magr;

        dux = pdist( ...
            U_now, ...
            @dist_du);

        duy = pdist( ...
            V_now, ...
            @dist_du);

        dul = dux.*rx+duy.*ry;
        dut = duy.*rx-dux.*ry;

        %% Convert to columns

        dist_now = dist_now(:);
        dul = dul(:);
        dut = dut(:);
        magr = magr(:);

        good = ...
            isfinite(dist_now) & ...
            isfinite(dul) & ...
            isfinite(dut) & ...
            isfinite(magr) & ...
            magr>0;

        if ~any(good)
            continue;
        end

        dist_now = dist_now(good);
        dul = dul(good);
        dut = dut(good);

        %% Separation bins

        scale_id = discretize( ...
            dist_now, ...
            dist_bin);

        good_scale = ...
            isfinite(scale_id) & ...
            scale_id>=1 & ...
            scale_id<=nScale;

        if ~any(good_scale)
            continue;
        end

        scale_id = scale_id(good_scale);
        dul = dul(good_scale);
        dut = dut(good_scale);

        %% Structure-function samples

        sf1_sample = dul;
        sf2ll_sample = dul.^2;
        sf2tt_sample = dut.^2;

        sf3lll_sample = dul.^3;
        sf3ltt_sample = dul.*dut.^2;

        % Homogeneity definition in Appendix C:
        % local longitudinal third moment
        sf3_homogeneity_sample = sf3lll_sample;

        %% Accumulate local block statistics

        block_vector = ...
            ib*ones(size(scale_id));

        linear_id = sub2ind( ...
            [nScale,nBlock], ...
            scale_id, ...
            block_vector);

        temp = accumarray( ...
            linear_id, ...
            sf1_sample, ...
            [nScale*nBlock,1], ...
            @sum,0);

        sum_SF1_block = ...
            sum_SF1_block + ...
            reshape(temp,nScale,nBlock);

        temp = accumarray( ...
            linear_id, ...
            sf2ll_sample, ...
            [nScale*nBlock,1], ...
            @sum,0);

        sum_SF2_block = ...
            sum_SF2_block + ...
            reshape(temp,nScale,nBlock);

        temp = accumarray( ...
            linear_id, ...
            sf3_homogeneity_sample, ...
            [nScale*nBlock,1], ...
            @sum,0);

        sum_SF3_block = ...
            sum_SF3_block + ...
            reshape(temp,nScale,nBlock);

        temp = accumarray( ...
            linear_id, ...
            ones(size(linear_id)), ...
            [nScale*nBlock,1], ...
            @sum,0);

        pair_count = ...
            pair_count + ...
            reshape(temp,nScale,nBlock);

        %% Overall estimates from the same selected samples

        sum_SF1_total = ...
            sum_SF1_total + ...
            accumarray( ...
                scale_id, ...
                sf1_sample, ...
                [nScale,1], ...
                @sum,0);

        sum_SF2ll_total = ...
            sum_SF2ll_total + ...
            accumarray( ...
                scale_id, ...
                sf2ll_sample, ...
                [nScale,1], ...
                @sum,0);

        sum_SF2tt_total = ...
            sum_SF2tt_total + ...
            accumarray( ...
                scale_id, ...
                sf2tt_sample, ...
                [nScale,1], ...
                @sum,0);

        sum_SF3lll_total = ...
            sum_SF3lll_total + ...
            accumarray( ...
                scale_id, ...
                sf3lll_sample, ...
                [nScale,1], ...
                @sum,0);

        sum_SF3ltt_total = ...
            sum_SF3ltt_total + ...
            accumarray( ...
                scale_id, ...
                sf3ltt_sample, ...
                [nScale,1], ...
                @sum,0);

        count_total = ...
            count_total + ...
            accumarray( ...
                scale_id, ...
                ones(size(scale_id)), ...
                [nScale,1], ...
                @sum,0);
    end
end

pair_runtime = toc;

fprintf( ...
    'Pair calculation completed in %.1f s\n', ...
    pair_runtime);

%% 12. Overall structure functions

SF1 = nan(nScale,1);
SF2ll = nan(nScale,1);
SF2tt = nan(nScale,1);
SF3lll = nan(nScale,1);
SF3ltt = nan(nScale,1);

valid_total = count_total>0;

SF1(valid_total) = ...
    sum_SF1_total(valid_total) ./ ...
    count_total(valid_total);

SF2ll(valid_total) = ...
    sum_SF2ll_total(valid_total) ./ ...
    count_total(valid_total);

SF2tt(valid_total) = ...
    sum_SF2tt_total(valid_total) ./ ...
    count_total(valid_total);

SF3lll(valid_total) = ...
    sum_SF3lll_total(valid_total) ./ ...
    count_total(valid_total);

SF3ltt(valid_total) = ...
    sum_SF3ltt_total(valid_total) ./ ...
    count_total(valid_total);

SF2 = SF2ll+SF2tt;
SF3 = SF3lll+SF3ltt;

%% 13. Local moments in each spatial block

local_SF1 = nan(nScale,nBlock);
local_SF2 = nan(nScale,nBlock);
local_SF3 = nan(nScale,nBlock);

valid_local = pair_count>=min_pairs;

local_SF1(valid_local) = ...
    sum_SF1_block(valid_local) ./ ...
    pair_count(valid_local);

local_SF2(valid_local) = ...
    sum_SF2_block(valid_local) ./ ...
    pair_count(valid_local);

local_SF3(valid_local) = ...
    sum_SF3_block(valid_local) ./ ...
    pair_count(valid_local);

%% 14. Calculate spatial homogeneity

[H1,mean_SF1,std_SF1,rms_SF1,nvalid1] = ...
    calculate_H( ...
        local_SF1, ...
        pair_count, ...
        min_pairs, ...
        min_valid_blocks);

[H2,mean_SF2,std_SF2,rms_SF2,nvalid2] = ...
    calculate_H( ...
        local_SF2, ...
        pair_count, ...
        min_pairs, ...
        min_valid_blocks);

[H3,mean_SF3,std_SF3,rms_SF3,nvalid3] = ...
    calculate_H( ...
        local_SF3, ...
        pair_count, ...
        min_pairs, ...
        min_valid_blocks);

%% 15. Save

outputname = [ ...
    input_dir, ...
    Case, ...
    '_pars_P', ...
    num2str(num_to_select), ...
    'T', ...
    num2str(timerange(end)), ...
    '_gridBlockHL.mat'];

save( ...
    outputname, ...
    'Case', ...
    'nparticles_file', ...
    'num_to_select', ...
    'selected_indices', ...
    'seconds', ...
    'dt', ...
    'timerange', ...
    'xscale', ...
    'Th_all', ...
    'x_domain', ...
    'y_domain', ...
    'x_edges', ...
    'y_edges', ...
    'nblock_x', ...
    'nblock_y', ...
    'nBlock', ...
    'max_particles_per_block', ...
    'min_pairs', ...
    'min_valid_blocks', ...
    'dist_axis', ...
    'dist_bin', ...
    'SF1', ...
    'SF2', ...
    'SF2ll', ...
    'SF2tt', ...
    'SF3', ...
    'SF3lll', ...
    'SF3ltt', ...
    'local_SF1', ...
    'local_SF2', ...
    'local_SF3', ...
    'H1', ...
    'H2', ...
    'H3', ...
    'mean_SF1', ...
    'mean_SF2', ...
    'mean_SF3', ...
    'std_SF1', ...
    'std_SF2', ...
    'std_SF3', ...
    'rms_SF1', ...
    'rms_SF2', ...
    'rms_SF3', ...
    'nvalid1', ...
    'nvalid2', ...
    'nvalid3', ...
    'pair_count', ...
    'count_total', ...
    'particle_count', ...
    'pair_runtime');

fprintf('Saved:\n%s\n',outputname);

%% ============================================================
% Local function
%% ============================================================

function [H,m,s,rms_value,nvalid] = ...
    calculate_H( ...
        local_SF, ...
        pair_count, ...
        min_pairs, ...
        min_valid_blocks)

    nScale = size(local_SF,1);

    H = nan(nScale,1);
    m = nan(nScale,1);
    s = nan(nScale,1);
    rms_value = nan(nScale,1);
    nvalid = zeros(nScale,1);

    for ir = 1:nScale

        valid = ...
            pair_count(ir,:)>=min_pairs & ...
            isfinite(local_SF(ir,:));

        values = local_SF(ir,valid);

        nvalid(ir) = numel(values);

        if nvalid(ir)<min_valid_blocks
            continue;
        end

        m(ir) = mean(values);

        % Population standard deviation
        s(ir) = std(values,1);

        rms_value(ir) = ...
            sqrt(mean(values.^2));

        denominator = ...
            abs(m(ir))+rms_value(ir);

        if isfinite(denominator) && denominator>0
            H(ir) = s(ir)/denominator;
        end
    end
end
