function saveResults(fname, ii, dist_axis, nvaild, ...
                    SF1l, SF1t, SF2ll, SF2tt, ...
                    SF3ltt, SF3lll, time_batch, total_steps)
    % 创建文件名
    save_fname = [fname(1:end-3), 'chunk', num2str(ii, '%02d'), 'SF123.mat'];
    
    % 保存数据
    save(save_fname, 'dist_axis', 'nvaild', ...
         'SF1l', 'SF1t', 'SF2ll', 'SF2tt', ...
         'SF3ltt', 'SF3lll', 'time_batch', 'total_steps', '-v7.3');
end
